In [1]:
import nibabel as nib
import numpy as np
import os
np.set_printoptions(precision=4, suppress=True)

In [2]:
img = nib.load('../sample_img/labels-028.nii.gz')

In [3]:
img

In [4]:
img.affine

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
print(img.header)

<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b''
dim_info        : 0
dim             : [  3 512 512 129   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : int16
bitpix          : 16
slice_start     : 0
pixdim          : [1. 1. 1. 1. 1. 1. 1. 1.]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 0
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b'None'
aux_file        : b'None'
qform_code      : unknown
sform_code      : aligned
quatern_b       : 0.0
quatern_c       : 0.0
quatern_d       : 0.0
qoffset_x       : 0.0
qoffset_y       : 0.0
qoffset_z       : 0.0
srow_x          : [1. 0. 0. 0.]
srow_y          :

In [6]:
nib.is_proxy(img.dataobj)

True

In [7]:
img_data = img.get_fdata()

In [8]:
unique,counts = np.unique(img_data,return_counts=True)

In [9]:
unique,counts

(array([0., 1., 3., 4., 5.]),
 array([27758042,  2865131,  1814305,   421663,   957435], dtype=int64))

In [10]:
np.isclose(img_data,2.0).sum()

0

In [11]:
new_data = np.isclose(img_data,2.0)

In [12]:
new_img = nib.Nifti1Image(new_data,img.affine,img.header)

In [13]:
nib.save(new_img,'img_smth.nii.gz')

In [14]:
img_dup = nib.load('../sample_img/labels-021.nii.gz')
img_dup2 = nib.load('img_smth.nii.gz')

In [15]:
img_dup2.get_fdata().dtype

dtype('float64')

In [16]:
np.allclose(img_dup.get_fdata(),img_dup2.get_fdata())

False